<?php

namespace Fnp\AdminBundle\Repository;

/**
 * ReleaseNoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReleaseNoteRepository extends \Doctrine\ORM\EntityRepository
{
    public function getNotesQuery()
    {
        $em = $this->getEntityManager();
        $dql = "SELECT a FROM FnpAdminBundle:ReleaseNote a ORDER BY a.id DESC";
        return $query = $em->createQuery($dql);
    }
}
